version: 0.2

phases:
  install:
    commands:
      - echo Installing Mocha...
      - npm install -g mocha
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install unit.js
      - npm install express
      - echo Logging in to Docker Hub...
      - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - mocha test/
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $IMAGE_REPO_NAME:$IMAGE_TAG
artifacts:
  files:
    - */*